server:
  port: 8888

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: exercise-service #?????????? ????????????? ????????.
          uri: lb://EXERCISE-SERVICE # ????? ???????? ???????, ???????????? ? ??????? LoadBalancer (lb://)
          predicates: #???????, ?? ??????? ??????? ????? ???????????? ? ???????????? ??????
          #(????????, ??? ??????? ?? /users/** ?????? ? USER-SERVICE).
            - Path=/exercise/**

        - id: program-service
          uri: lb://PROGRAM-SERVICE
          predicates:
            - Path=/program/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true