server:
  port: 8082

spring:
  application:
    name: EXERCISE-SERVICE
  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:h2:mem:exercise-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # ????????????? ????????? ? ????????? ???????
    show-sql: true      # ?????????? SQL-??????? ? ?????
  h2:
    console:
      enabled: true      # ???????? H2-??????? (http://localhost:8082/h2-console)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # ????? Eureka Server
    register-with-eureka: true  # ?????????????? ?????? ? Eureka
    fetch-registry: true        # ???????? ?????? ???????? ?? Eureka
